// nolint
package wasm

import (
	"github.com/sikkatech/centre-zone/x/bank/keeper"
	"github.com/sikkatech/centre-zone/x/bank/types"
)

// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/cosmwasm/wasmd/x/wasm/internal/keeper/
// ALIASGEN: github.com/cosmwasm/wasmd/x/wasm/internal/types/

const (
	// GasMultiplier         = keeper.GasMultiplier
	// MaxGas                = keeper.MaxGas
	// QueryListContracts    = keeper.QueryListContracts
	// QueryGetContract      = keeper.QueryGetContract
	// QueryGetContractState = keeper.QueryGetContractState
	// QueryGetCode          = keeper.QueryGetCode
	// QueryListCode         = keeper.QueryListCode
	// DefaultCodespace      = types.DefaultCodespace
	ModuleName            = types.ModuleName
	StoreKey              = types.StoreKey
	TStoreKey             = types.TStoreKey
	QuerierRoute          = types.QuerierRoute
	RouterKey             = types.RouterKey
)

var (
	// functions aliases
	// NewKeeper                 = keeper.NewKeeper
	// NewQuerier                = keeper.NewQuerier
	// MakeTestCodec             = keeper.MakeTestCodec
	// CreateTestInput           = keeper.CreateTestInput
	// RegisterCodec             = types.RegisterCodec
	// ErrCreateFailed           = types.ErrCreateFailed
	// ErrAccountExists          = types.ErrAccountExists
	// ErrInstantiateFailed      = types.ErrInstantiateFailed
	// ErrExecuteFailed          = types.ErrExecuteFailed
	// ErrGasLimit               = types.ErrGasLimit
	// ErrInvalidGenesis         = types.ErrInvalidGenesis
	// GetCodeKey                = types.GetCodeKey
	// GetContractAddressKey     = types.GetContractAddressKey
	// GetContractStorePrefixKey = types.GetContractStorePrefixKey
	// NewCodeInfo               = types.NewCodeInfo
	// NewParams                 = types.NewParams
	// NewWasmCoins              = types.NewWasmCoins
	// NewContractInfo           = types.NewContractInfo
	// CosmosResult              = types.CosmosResult

	// // genesis aliases
	// ValidateGenesis = types.ValidateGenesis
	// InitGenesis     = keeper.InitGenesis
	// ExportGenesis   = keeper.ExportGenesis

	// // variable aliases
	// ModuleCdc           = types.ModuleCdc
	// KeyLastCodeID       = types.KeyLastCodeID
	// KeyLastInstanceID   = types.KeyLastInstanceID
	// CodeKeyPrefix       = types.CodeKeyPrefix
	// ContractKeyPrefix   = types.ContractKeyPrefix
	// ContractStorePrefix = types.ContractStorePrefix
)

type (
	// Keeper                 = keeper.Keeper
	// GetCodeResponse        = keeper.GetCodeResponse
	// MsgStoreCode           = types.MsgStoreCode
	// MsgInstantiateContract = types.MsgInstantiateContract
	// MsgExecuteContract     = types.MsgExecuteContract
	// CodeInfo               = types.CodeInfo
	// ContractInfo           = types.ContractInfo

	// GenesisState = types.GenesisState
)